# Generated by Django 5.0.7 on 2024-07-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundaoCirurgicoTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('subtext', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('processed', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
